apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: edge
resources:
  - ../../base
images:
  - name: asia-northeast1-docker.pkg.dev/asoview-clone-dev/asoview-clone/gateway
    newTag: "7fc097c"
patches:
  - target:
      kind: Deployment
      name: gateway
    patch: |
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: RESERVATION_SERVICE_URI
          value: http://reservation-service.core-services.svc.cluster.local:8083
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: TICKETING_SERVICE_URI
          value: http://ticketing-service.core-services.svc.cluster.local:8082
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: COMMERCE_CORE_URI
          value: http://commerce-core.core-services.svc.cluster.local:8081
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: SEARCH_SERVICE_URL
          value: http://search-service.search.svc.cluster.local:8082
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: ANALYTICS_INGEST_URI
          value: http://analytics-ingest.data-jobs.svc.cluster.local:8085
