apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ticketing-service
  namespace: core-services
spec:
  podSelector:
    matchLabels:
      app: ticketing-service
  policyTypes: ["Ingress", "Egress"]
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: edge
      ports:
        - protocol: TCP
          port: 8082
  egress:
    - {}
