apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: urakata-reservation-web
  namespace: operator-web
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: urakata-reservation-web
