apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: commerce-core
  namespace: core-services
spec:
  podSelector:
    matchLabels:
      app: commerce-core
  policyTypes: ["Ingress", "Egress"]
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: edge
          podSelector:
            matchLabels:
              app: gateway
        - namespaceSelector:
            matchLabels:
              name: core-services
      ports:
        - protocol: TCP
          port: 8081
  egress:
    # DNS
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: UDP
          port: 53
    # Cloud SQL Auth Proxy via 127.0.0.1 (sidecar) and Spanner/Stripe egress to internet
    - {}
