apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ads-service
  namespace: ads-services
spec:
  podSelector:
    matchLabels:
      app: ads-service
  policyTypes: ["Ingress", "Egress"]
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: edge
      ports:
        - protocol: TCP
          port: 8084
  egress:
    - {}
