apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: web
  namespace: edge
spec:
  podSelector:
    matchLabels:
      app: web
  policyTypes: ["Ingress", "Egress"]
  ingress:
    - {}
  egress:
    - {}
